[package]
name = "sp1-guest"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "sp1-guest"
path = "src/main.rs"

[dependencies]
sp1-zkvm = { version = "6.0.0" }
ed25519-dalek = { version = "2.1", default-features = false, features = ["alloc"] }
